[package]
name = "rap"
version = "0.3.9"
edition = "2024"

[workspace]
members = ["lib/rap-engine", "rap-tui", "lib/rap-store"]

[workspace.dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
anyhow = "1.0.104"

[dependencies]
rap-engine = { path = "lib/rap-engine" }
tokio = { workspace = true }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
